name: Gerar APK Android

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Montar jogo
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Baixar construtor oficial
        run: docker pull ghcr.io/kivy/buildozer:latest

      - name: Gerar APK
        run: |
          docker run --rm \
            -e APP_ANDROID_NDK=29 \
            -v "${{ github.workspace }}:/home/user/hostcwd" \
            ghcr.io/kivy/buildozer:latest \
            android debug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: jogo-apk
          path: bin/*.apk
          if-no-files-found: error
